version: '3.8'

services:

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.1
    container_name: elasticsearch
    tty: true
    privileged: true
    stdin_open: true
    environment:
      - node-name=elastic
      - discovery.type=single-node
      - xpack.security.enabled=false
      - discovery.type=single-node
      - cluster.routing.allocation.enable=all
      - ELASTIC_PASSWORD=password
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.3.2
    container_name: es_kibana
    volumes:
      - kibanadata:/usr/share/kibana/data
    ports:
      - 5601:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=password
      - XPACK_SECURITY_ENABLED=false
      - ELASTICSEARCH_HOST=http://elastic:9200
    depends_on:
      - elastic

volumes:
  esdata: {}
  kibanadata: {}